
-- 1. Add tenant_id column to cuts_history_backfill
ALTER TABLE public.cuts_history_backfill
  ADD COLUMN IF NOT EXISTS tenant_id uuid;

-- 2. Backfill existing rows: all 10 existing periods belong to Bitec (the user ran them while logged in as Bitec)
UPDATE public.cuts_history_backfill
SET tenant_id = 'c10e00fe-c1f6-423e-85db-8996c65dc1b6'
WHERE tenant_id IS NULL;

-- Make tenant_id mandatory
ALTER TABLE public.cuts_history_backfill
  ALTER COLUMN tenant_id SET NOT NULL;

-- 3. Drop old (period) unique constraint and add (period, tenant_id)
DO $$
DECLARE
  cons_name text;
BEGIN
  SELECT conname INTO cons_name
  FROM pg_constraint
  WHERE conrelid = 'public.cuts_history_backfill'::regclass
    AND contype = 'u'
    AND pg_get_constraintdef(oid) LIKE '%(period)';
  IF cons_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.cuts_history_backfill DROP CONSTRAINT %I', cons_name);
  END IF;
END $$;

-- Drop unique index on period if it exists outside of a constraint
DROP INDEX IF EXISTS public.cuts_history_backfill_period_key;

ALTER TABLE public.cuts_history_backfill
  ADD CONSTRAINT cuts_history_backfill_period_tenant_key UNIQUE (period, tenant_id);

-- 4. Replace permissive RLS with tenant-scoped policies
DROP POLICY IF EXISTS "Authenticated can insert backfill" ON public.cuts_history_backfill;
DROP POLICY IF EXISTS "Authenticated can read backfill"   ON public.cuts_history_backfill;
DROP POLICY IF EXISTS "Authenticated can update backfill" ON public.cuts_history_backfill;

CREATE POLICY "Tenant can read backfill"
  ON public.cuts_history_backfill
  FOR SELECT
  TO authenticated
  USING (tenant_id = public.get_user_tenant_id());

CREATE POLICY "Tenant can insert backfill"
  ON public.cuts_history_backfill
  FOR INSERT
  TO authenticated
  WITH CHECK (tenant_id = public.get_user_tenant_id());

CREATE POLICY "Tenant can update backfill"
  ON public.cuts_history_backfill
  FOR UPDATE
  TO authenticated
  USING (tenant_id = public.get_user_tenant_id())
  WITH CHECK (tenant_id = public.get_user_tenant_id());

-- Service role full access (used by edge function)
CREATE POLICY "Service can manage backfill"
  ON public.cuts_history_backfill
  FOR ALL
  TO public
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- 5. Cleanup: 182 orphan device_cuts_history rows (tenant_id IS NULL)
-- These were generated by KLAZ-as-user invoking backfill that ran as Bitec; data is unusable as-is.
DELETE FROM public.device_cuts_history WHERE tenant_id IS NULL;
